version: "3.9"

services:

  api-gateway:
    build:
      context: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    env_file:
      - ./services/api-gateway/.env

  mock-exchange:
    build:
      context: ./services/mock-exchange
    container_name: mock-exchange
    ports:
      - "9000:9000"
    restart: unless-stopped

  telemetry-service:
    build:
      context: ./services/telemetry-service
    container_name: telemetry-service
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    env_file:
    - ./services/telemetry-service/.env

  bot-worker:
    build:
      context: ./services/bot-worker
    container_name: bot-worker
    restart: unless-stopped
    depends_on:
      - mock-exchange
      - redis
    env_file:
    - ./services/bot-worker/.env

  benchmark-service:
    build:
      context: ./services/benchmark-service
    container_name: benchmark-service
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./services/benchmark-service/.env

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iicpc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./deployments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - mock-exchange
  
  grafana:
    image: grafana/grafana
    container_name: grafana

    restart: unless-stopped

    ports:
      - "3000:3000"

    depends_on:
      - prometheus

  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor

    restart: unless-stopped

    ports:
      - "8088:8080"

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

    privileged: true



  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter

    restart: unless-stopped

    ports:
      - "9121:9121"

    environment:
      REDIS_ADDR: redis://redis:6379

    depends_on:
      - redis



  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter

    restart: unless-stopped

    ports:
      - "9187:9187"

    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:password@postgres:5432/iicpc?sslmode=disable"

    depends_on:
      - postgres
    


volumes:
  postgres_data: