export const endpoints = {
  health: '/health',
  authLogin: '/auth/login',
  authLogout: '/auth/logout',
  authRegister: '/auth/register',
  authProfile: '/auth/me',
  benchmarkSessions: '/benchmarks',
  benchmarkDetail: (id: string) => `/benchmarks/${id}`,
  benchmarkReplay: (id: string) => `/replay?benchmarkId=${id}`,
  leaderboard: '/leaderboard',
  leaderboardTop: '/leaderboard/top',
  leaderboardTeam: (team: string) => `/leaderboard/team/${encodeURIComponent(team)}`,
  leaderboardBenchmark: (id: string) => `/leaderboard/benchmark/${id}`,
  telemetrySummary: '/telemetry/summary',
  telemetryHistory: '/history',
  workers: '/workers',
  infrastructure: '/infrastructure',
  redis: '/infrastructure/redis',
  postgres: '/infrastructure/postgres',
  logs: '/logs',
  notifications: '/notifications',
  submissions: '/submissions',
  deployments: '/deployments',
}
